name: Notify IRC

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  notify-irc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions
        run: chmod +x .github/workflows/notify-irc.sh

      - name: Run Notify IRC Script
        run: |
          .github/workflows/notify-irc.sh "$COMMITS_JSON" "$ACTOR" "$BRANCH" "$COMPARE_URL" | notify-irc \
            --channel "#OpenZFS-Windows" \
            --server "irc.libera.chat" \
            --nickname zfs-consus

