name: Notify IRC

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  notify-irc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions
        run: chmod +x .github/workflows/notify-irc.sh

      - name: Generate notification message
        id: notify
        run: |
              .github/workflows/notify-irc.sh "$COMMITS_JSON" "$GITHUB_ACTOR" "$GITHUB_REF_NAME" "$GITHUB_COMPARE_URL"

      - name: Decode Message for IRC Notify
        id: decode-message
        run: |
              ENCODED_MESSAGE="VGVzdCBsaW5lIG9uZQpUZXN0IGxpbmUgdHdvCg=="
              echo "message=$ENCODED_MESSAGE" >> $GITHUB_OUTPUT

      - name: Notify IRC
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#OpenZFS-Windows"
          server: "irc.libera.chat"
          nickname: "zfs-consus"
          message: ${{ steps.encode-message.outputs.message }} | base64 --decode 
