name: "Notify IRC on Push"

on:
  push:
    branches:
      - main
      - development

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify IRC
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#OpenZFS-Windows"
          server: "irc.libera.chat"
          nickname: zfs-consus
          message: |
            [openzfs] ${{ github.actor }} pushed ${{ github.event.commits && github.event.commits.size || 0 }} commit${{ github.event.commits && github.event.commits.size > 1 && 's' || '' }} to ${{ github.ref_name }}
            ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message.split('\n')[0], '\n') }}

