name: Notify IRC

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  notify-irc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions
        run: chmod +x .github/workflows/notify-irc.sh

      - name: Generate notification message
        id: notify
        run: |
          ENCODED_MESSAGE="$(.github/workflows/notify-irc.sh | jq -R .)"
          echo "Encoded is $ENCODED_MESSAGE"
          echo "message=$ENCODED_MESSAGE" >> $GITHUB_OUTPUT

      - name: Notify IRC
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#OpenZFS-Windows"
          server: "irc.libera.chat"
          nickname: "zfs-consus"
          message: ${{ fromJSON(steps.encode-message.outputs.message) }}


