
name: Notify IRC on Push

on:
  push:
  issues:
    types:
      - opened
      - edited
      - closed
  issue_comment:
      
jobs:
  notify-irc:
    runs-on: ubuntu-latest

    steps:
      - name: Notify IRC
        uses: openzfsonwindows/notify-irc@master
        with:
          channel: "#OpenZFS-Windows"
          server: "irc.libera.chat"
          nickname: "zfs-consus"
          ansicolor: "true"
          eventpath: ${{ github.event_path }}

