name: "Notify IRC on Push"

on:
  push:
    branches:
      - main
      - development

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Notify IRC
        env:
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
          ACTOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          COMPARE_URL: ${{ github.event.compare }}
        run: |
          .github/workflows/notify-irc.sh "$COMMITS_JSON" "$ACTOR" "$BRANCH" "$COMPARE_URL" | notify-irc \
            --channel "#OpenZFS-Windows" \
            --server "irc.libera.chat" \
            --nickname zfs-consus

