name: "Notify IRC on Push"

on:
  push:
    branches:
      - main
      - development

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify IRC
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#OpenZFS-Windows"
          server: "irc.libera.chat"
          nickname: zfs-consus
          message: |
            [openzfs] ${{ github.actor }} pushed ${{ github.event.commits && github.event.commits | length || '0' }} commit${{ github.event.commits && github.event.commits.length > 1 && 's' || '' }} to ${{ github.ref_name }}
            ${{ github.event.compare }}
            ${{ format('{0}', github.event.commits[0].message) }}...
            ${{ github.event.commits.length > 8 && '...and more!' || '' }}

